project:
  type: website
  output-dir: ../docs/

website:
  title: ""
  navbar:
    left:
      - text: "Home"
        file: index.html
      - text: "EXO View"
        file: exoView.html
      - text: "EXO Plot"
        file: exoPlot.html
    right:
      - icon: github
        href: https://github.com/marine-ecologist/exo
        aria-label: GitHub

format:
  html:
    theme: cosmo
    toc: true
